### PR TITLE
Display active search filters

### PR DESCRIPTION
**Pull request by gabiseabra**
## After

simulator screen shot - iphone 6 - 2018-04-26 at 16 53 01

### CODE REVIEW

**Comment by gusaiani** [comment]
@gabiseabra,

let's use `0-6M` instead of `≤ 6M` :)

`≤` is lovely indeed, but only we nerds understand it ;D

**Comment by gusaiani** [comment]
@gabiseabra, 

for `≥ 3M`, I think `3M+` is understandable by more people as well.

**Comment by gusaiani** [comment]
@gabiseabra Did you notice there's a new icon, and the asset is in the Invision page for this layout?

**Comment by gusaiani** [comment]
@gabiseabra 

The "bleeding" of images around the filter box is something I've been looking at these past few days.

Shall we try having the filter box be full width, and also at the very top? I feel it will be cleaner after all.

image

**Comment by gusaiani** [comment]
@gabiseabra 

With this, we can drop the box-shadow around the filter box.

**Comment by gabiseabra** [comment]
## No filters

simulator screen shot - iphone 6 - 2018-04-26 at 17 37 29

## Search form

simulator screen shot - iphone 6 - 2018-04-26 at 17 36 07

## Active filters

simulator screen shot - iphone 6 - 2018-04-26 at 17 36 10

**Pull request merged**
